version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
