version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - "5433:5432"  # Expose PostgreSQL on local port 5433
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  java-app:
    build:
      context: .  # Build the image from the current directory using the Dockerfile
    container_name: javaApp
    ports:
      - "8085:8085"  # Ensure port consistency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/my_database  # Use the correct hostname of the 'postgres' service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - postgres
    command: java -jar app.jar  # Match the JAR name specified in the Dockerfile
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
